# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'red'), ('green', 'green'), ('blue', 'blue')], max_length=100)),
                ('color_next', models.CharField(choices=[('yello', 'yellow'), ('purple', 'purple'), ('black', 'black')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
